### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by timkendall** [kagis/pgwire#10]
First off this is awesome work - we've been looking for a simpler alternative to Debezium that supported pgoutput for logical decoding. This fits the bill perfectly (and it's Node with 0 deps!).

You knew this was coming but what are your thoughts on converting this library to TypeScript? I would love to open some PR's to help.

**Comment by exe-dealer** [comment]
I don't want introduce any mandatory build step because it makes impossible to use this package as zip/git dependency (and i don't like typescript). But api is designed to support static type checking and I was thinking about creating .d.ts file for pgwire so I can accept PR with .d.ts file only.

**Comment by timkendall** [comment]
Sounds good, thanks.

**Comment by vitaly-t** [comment]
> I don't want introduce any mandatory build step because it makes impossible to use this package as zip/git dependency

No it doesn't. Distribution of TypeScript-written libraries is well-evolved today, and it does not require any extra step during installation. I have been writing and deploying a lot of TypeScript packages, so trust me on this.

>  i don't like typescript

You will find this attitude not working for you long-term. I was in the same boat some time ago, but after a number of serious projects in TypeScript I would not go back to JavaScript.

Also, more and more developers want TypeScript support today, which includes those who develop for PostgreSQL under Node.js. Trust me on this, I am seeing the usage statistics for my library, people prefer TypeScript nowadays.

From the author of [pg-promise](https://github.com/vitaly-t/pg-promise). Nice job, b.t.w. ;)

**Comment by exe-dealer** [comment]
> No it doesn't. Distribution of TypeScript-written libraries is well-evolved today, and it does not require any extra step during installation.

How can I use unbuilded TypeScript lib as git/zip dependency in our JavaScript projects?

- build while `npm install` (if it possible it needs to install typescript package and manage typescript deletion after build)
- prebuild every commit (produces a lot of noise in repo history)

All this options are not elegant. Do I miss some other option?

Its important for me to be able to use pgwire as git/zip dependency in js projects because I can deploy our private projects more quick without waiting for CI jobs and publishing to npm. And there is no need to bloat npm with versions per commit

**Comment by vitaly-t** [comment]
When you write something in TypeScript these days, it is deployed as JavaScript, with auto-generated TypeScript declarations. Everything gets ready as you prepare your package for publishing. It is is very-very easy today.

There are plenty of tutorials out there of how to set up a TypeScript project. And I gave you one of my own examples there - [connection-string](https://github.com/vitaly-t/connection-string).

**Comment by dko-slapdash** [comment]
Confirming, TypeScript is super-awesome in 2019. One week writing TypeScript code, and one won't be back to pure JS ever.
