### ISSUE TITLE
Sending multiple single-queries through the same connection?

### ISSUE THREAD

**Issue by dko-slapdash** [kagis/pgwire#13]
The doc doesn't say if it's possible to do something like:

```js
const conn = await pgwire.connect(...);
await Promise.all([
  conn.query("first query"),
  conn.query("second query"),
  ...
  conn.query("nth query")
]);
```

(Of course, it's an artificial example, in real life all these queries come from different parts of the code, and some of them may spawn while other queries are still running.)

1. I suspect this is a totally working case, right? I.e. is it supported?
2. If the answer to (1) is "yes", then what about stream-like queries? Imagine I run two huge "SELECT * FROM tbl1" and "SELECT * FROM tbl2" on the same connection and then `for await` on both of resulting streams. Will it work? Or the 2nd stream won't start until the 1st one finishes?

**Comment by exe-dealer** [comment]
1 - Yes, it is supported. 

> for await on both of resulting streams. Will it work? Or the 2nd stream won't start until the 1st one finishes?

for await on both of resulting streams will work AND 2nd stream won't start until the 1st one finishes. But if you going to for await inside for await then deadlock occures and in this case it will not work

**Comment by dko-slapdash** [comment]
Thanks!
