### ISSUE TITLE
Feature request: Non-async pgwire.connect() version

### ISSUE THREAD

**Issue by dko-slapdash** [kagis/pgwire#15]
Currently, one has to await on pgwire.connect() (because it returns a Promise). This makes it impossible to be called in e.g. constructor of some other class, so I have to do the following hack:
```js
const Connection = require("pgwire/lib/connection");
...
constructor(...) {
  this.connection = new Connection({...});
}
```

I notices that pgwire.pool() does NOT required awaiting, and this is very convenient. I'd use pgwire.pool() everywhere instead of the above example, but unfortunately Pool doesn't allow to create new connections (see https://github.com/kagis/pgwire/issues/14 for more details).

**Comment by exe-dealer** [comment]
synchronous `pgconnection` is implemented
