### ISSUE TITLE
Feature request: support for “eager filtering” while reading from replication a slot

### ISSUE THREAD

**Issue by dko-slapdash** [kagis/pgwire#16]
Preface: in our setup, we have 5 replication slots and 5 independent workers reading the same publication (i.e. the same set of tables in the same publication). All of those 5 workers basically read the same streamed rows from Postgres, but then decide, should they process the row or not, by doing `id % 5 == N` (where N is worker number). This helps to achieve better parallelism.

But in some sense it’s a waste of CPU, because in all of those 5 workers, pgwire decodes the whole row, all the attributes. Although in 4 cases of 5 it needs to unpack just the 1st column (id), do this `% 5` comparison and, if the result doesn’t match the worker number, skip the row and save CPU on other attributes decoding. 

Would be great to have a callback which, if passed, is fed with the packed (raw) row buffer, and if it returns false, skips attributes decoding in this buffer.

**Comment by exe-dealer** [comment]
I think that better solution is to implement lazy decoding. Need to check if lazy decoding does not introduce significant overhead in common case

**Comment by BigsonLvrocha** [comment]
@exe-dealer any comments on #27 to close the issue?
