### ISSUE TITLE
pgoutput does not support message_cb, so pgwire can't work with pg_logical_emit_message() even theoretically

### ISSUE THREAD

**Issue by dko-slapdash** [kagis/pgwire#19]
This is FYI just for the history, for people who'll google for it in the future. Because pgoutput doesn't define any message_cb callback (since it's not needed for pub-sub replication purposes).

Proof: https://github.com/postgres/postgres/blob/9de77b5453130242654ff0b30a551c9c862ed661/src/backend/replication/pgoutput/pgoutput.c#L111-L117

In comparison to this, wal2json does support messages:
https://github.com/eulerto/wal2json/blob/master/wal2json.c#L221

**Comment by exe-dealer** [comment]
pgwire doesnot force you to use pgoutput. You can use raw message stream without calling `.pgoutput()` funcion. Here is example how to use `test_decoding` plugin https://github.com/kagis/pgwire#logical-replication

We use pg_logical_emit_message in our production with pgwire + our json decoder https://github.com/kagis/pg_json_decoding
wall2json will also work
