### ISSUE TITLE
Serialize and Deserialize a BigInt

### ISSUE THREAD

**Issue by carapai** [kagis/pgwire#26]
pgwire is not able to serialize bigint if the primary key is bigint

**Comment by exe-dealer** [comment]
in .query() or .logicalReplication() ?

**Comment by exe-dealer** [comment]
there is completely rewritten pgwire in `deno` branch, try to use it. It is compatible with nodejs, but you need to install it from github instead of npm

```
"dependencies": {
  "pgwire": "https://github.com/kagis/pgwire/archive/72b8f43ec25ba58a31f0c3e82862bf122f92df9c.tar.gz"
}
```
