### ISSUE TITLE
Logical Replication and Clustering

### ISSUE THREAD

**Issue by bobbyharmoney** [kagis/pgwire#33]
I am using logical replication and it works great.

My application will be deployed into Kubernetes with a replica count of 3. If 3 instances of my application is running, and all connecting to the same replication slot, does it mean all modification changes will be published to all instances of my application? 

Or does a replication slot allow 1 connection only? In which case, 2 application instances would fail to connect. 

Thanks in advance

**Comment by exe-dealer** [comment]
afaik replication slot allows only one consumer. Other connections will fail to start replication.

**Comment by bobbyharmoney** [comment]
Thanks @exe-dealer - will close this issue as it's not related to the library.
